name: Quality Control and Tests

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install packages
        run: yarn install

      - name: Run quality controls
        run: yarn quality-checks

      - name: Run tests
        run: yarn test
